### ISSUE TITLE
RFC: The Compensation Effect

### ISSUE THREAD

**Issue by dearsaturn** [social-native/kafka-sagas#162]
In the Saga pattern, compensation is a key aspect of the workflow. This RFC proposes a new effect for us to register compensation to be handled when a saga throws, which will not be subject to the overall timeout of the saga unless otherwise specified.

```ts
/** Eagerly send work to some other saga for compensation to be handled. */
type DistributedCompensator<Payload extends DefaultPayload> = {
    topic: string;
    payload: Payload;
}

/** Compensate with your own function, async function, or workflow (i.e. callable saga). */
type LocalCompensator<Payload extends DefaultPayload> = {
    handler: (payload: Payload) =>  void | Promise<void> | Generator<IEffectDescription, void, any>;
    payload: Payload;
}

type CompensationPlan<Payload> = DistributedCompensator<Payload> | LocalCompensator<Payload>;

type DeleteCampaignPayload = {campaign_id: string | number};

function* saga ({payload}, {context: {effects: {callFn, addCompensation}}}) {
    const campaignId = yield callFn(createCampaign, [{name: 'test_campaign'}]);

    yield addCompensation<DeleteCampaignPayload>({
        topic: topics.DELETE_CAMPAIGN,
        payload: {campaign_id: campaignId}
    });
}
```

**Comment by markrsocialnative** [comment]
```ts
async function runTripBookingSaga(payload) {
  const compensations = [];
  try {
    // bookAirline, bookHotel, and bookCar must be run at MOST once
    const airlineBookingId = await bookAirline(payload);
    compensations.push(() => cancelAirline(airlineBookingId));
    
    const hotelBookingId = await bookHotel(payload);
    compensations.push(() => cancelHotel(hotelBookingId));

    await bookCar(payload);
  catch(error) {
    // All compensations must be run at LEAST once (must be idempotent)
    await Promise.all(compensations.map(compensation => runUntilSuccess(compensation));
  }
}

// Don't look into this implementation, it's intentionally over-simplified.
// The important part is that all compensations eventually happen,
// and this function is the mechanism for that.
async function runUntilSuccess(compensation: () => Promise<void>): Promise<void> {
   const isSuccess = false;
   while (!isSuccess) {
     try {
       await compensation();
       isSuccess = true;
     } catch (error) {
        console.log(error);
     }
  }
}
```
I'm not proposing this as syntax, but I'm wondering how we'd accomplish this same task using our current / proposed syntax. In this design, the list of compensations is stored in memory, as a plain array. When it comes time to compensate, it's simple enough to see we just need to iterate through the list. Conveniently, the compensating functions are also stored in memory. Where is the list of compensations stored in our proposed design?

**Comment by dearsaturn** [comment]
In the propose design, the daemon running the saga/piping kafka messages into it (TopicSagaConsumer) would construct a map of K: `transactionId-partition-offset` (as unique to a particular message consume as you can get) to compensation chain (an array of `Compensation`). When the method linked in the OP `catch`es, the compensation chain for that particular message is sought out, the compensations are run from end to start if there are any, serially. So, `addCompensation` is essentially doing what you do in your example - pushing into some list whose lifetime is the message.

**Comment by tuandoansn** [comment]
The new compensation effects looks good to me, although I do want to see that implementation of the chain.

**Comment by markrsocialnative** [comment]
not sure if we want to even try to handle this case, but heres another thing about Sagas, in general, that I don't know how to solve. https://www.figma.com/file/Q8w07LL2UkyFvzVbrFgmEd/Untitled?node-id=0%3A1
